### ISSUE TITLE
[vehicule layer cdn]: Facing Challenges in Updating Vehicle Positions Dynamically

### ISSUE THREAD

**Issue by Elkarroudi** [belom88/visgl-addons#112]
Description:
Upon successfully initializing Mapbox and integrating a vehicle layer, and established a WebSocket connection to receive real-time vehicle data from an external API, we encountered challenges with updating vehicle positions dynamically based on data received via WebSocket. 

Problem Statement:
The main issue lies in the updating process. receiving real-time data from the WebSocket connection, we lack a robust mechanism to seamlessly update the vehicle positions on the map in real-time. 

Expected Behavior:
The vehicle's coordinates should be updated smoothly at regular intervals. and should move seamlessly across the map without any disruptions.

Code: 
"" document.addEventListener("DOMContentLoaded", async function () {

            const { MapboxOverlay, TextLayer, MapController } = deck;
            const MAPBOX_TOKEN = 'toekn';
            let latitude = 39.768458, longitude = -86.155231;
            async function getGeo () { return [{ latitude: latitude, longitude: longitude, bearing: -87.94099460927194, vehilceType: 1}]; }

            let map = new mapboxgl.Map({
                accessToken: MAPBOX_TOKEN,
                container: 'map',
                center: [longitude, latitude],
                zoom: 17,
                maxZoom: 17,
                pitch: 25,
                bearing: -17.6
            });

            map.on('load', async function () {

                let vehicleLayer = new VehicleLayer({
                    id: 'vehicle-layer',
                    data: await getGeo(),
                    sizeScale: 5,
                    dimensionMode: '3D',
                    getColor: [238, 255, 203],
                    getPosition: vehicle => [vehicle.longitude, vehicle.latitude],
                    getBearing: vehicle => vehicle.bearing,
                    getVehicleType: vehicle => vehicle.vehilceType,
                }

                let deckOverlay = new MapboxOverlay({ layers: [vehicleLayer, ] });
                map.addControl(deckOverlay);

            });
        }); ""

**Comment by belom88** [comment]
Hi, @Elkarroudi ! Nice to see you using my VehicleLayer. Is this issue actual for you right now?
Also, any feedback would be appreciated as well as nice to have feature requests.

**Comment by Elkarroudi** [comment]
Hi Viktor, yeah if you could help i would appreciate it , the problem that i have is in the animation, when the vehicle location change i won't go smoothly, what ever i do, could you do a simple example how can i integrate the animation you have implemented. and thank you !
