### ISSUE TITLE
Uncaught ReferenceError: VehicleLayer is not defined

### ISSUE THREAD

**Issue by gang-10** [belom88/visgl-addons#98]
i am coding with native javascript , i work with cdn "@belom88/vehicle-layer" Visualize transit vehicles , so when i call the script using new new VehicleLayer({}) i get this error map:1156 Uncaught ReferenceError: VehicleLayer is not defined
```

`<script src="https://unpkg.com/deck.gl@^8.0.0/dist.min.js"></script>
<script  src="https://cdn.jsdelivr.net/npm/@belom88/vehicle-layer"></script>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    function initializeMap() {
const MAPBOX_ACCESS_TOKEN =
  'pk.eyJ1Ijoic2FhZG92c2t5IiwiYSI6ImNsZ3VxeDJ0bTBvMDYzZm81cWd2YWpkNTEifQ.rT0oeL7LOwbvkPYCFSVFWQ';


const AIR_PORTS =
  'https://d2ad6b4ur7yvpq.cloudfront.net/naturalearth-3.3.0/ne_10m_airports.geojson';

const deckgl = new deck.DeckGL({
  container: 'map',
  // Set your Mapbox access token here
  mapboxApiAccessToken: 'pk.eyJ1Ijoic2FhZG92c2t5IiwiYSI6ImNsZ3VxeDJ0bTBvMDYzZm81cWd2YWpkNTEifQ.rT0oeL7LOwbvkPYCFSVFWQ',
  initialViewState: {
    longitude: -122.4,
    latitude: 37.74,
    zoom: 5,
    maxZoom: 10,
    pitch: 30,
    bearing: 0
  },
  controller: true,
  layers: [
    new VehicleLayer({
      id: 'vehicle-layer',
      data: [
        {
          latitude: 53.43185529968051,
          longitude: -2.9577037905967574,
          bearing: -51.94099460927194,
          vehilceType: VehicleType.TransitBus,
        },
        {
          latitude: 53.431755073582494,
          longitude: -2.9578708705967136,
          bearing: -51.94099460927194,
          vehilceType: VehicleType.Tram,
        },
      ],
      dimensionMode: '3D',
      getColor: [238, 255, 203],
      getPosition: (vehicle) => [vehicle.longitude, vehicle.latitude],
      getBearing: (vehicle) => vehicle.bearing,
      getVehicleType: (vehicle) => vehicle.vehilceType,
    }),

  ]
});
}
    initializeMap();
});
</script>
```

`
any help *

**Comment by ZerroukZakaria** [comment]
I encountered the same problem. I would really appreciate if someone helped with this.

**Comment by belom88** [comment]
I didn't test it as a scripting library. I will take a look this week. I appreciate you interest to VehicleLayer. Thanks.

**Comment by belom88** [comment]
I took a look at the problem.
I've made v0.1.6 that adds `VehicleLayer` to `window` global variable
Unfortunately, this wasn't enough, the bundle contain `import` statements that fail. I need to make a special build for scripting API that will import variable from global scope intead of importing them.
I will make it as soon as possible. Probably, this week.

**Comment by belom88** [comment]
The issue has been resolved in v0.1.7.
You can use deck.gl scripting API with a "scripting bundle" version of VehicleLayer. You just need to add "scripting-bundle.js" to your webpage. 
For example 
```
<script src="https://unpkg.com/@belom88/vehicle-layer@0.1.7/scripting-bundle.js"></script>
```
I've created an example on codepen: https://codepen.io/belom88/pen/VwVNYwb

**Comment by gang-10** [comment]
Thank you very much for your assistance. I tested the code, and the script worked perfectly.

**Comment by gang-10** [comment]
Hello ,
I attempted to implement live tracking using deck.gl with vehicleLayer, along with scripting tags and AnimationWorker from 'Leaders.gl/worker-utils', yet encountered challenges in achieving the desired smoothness. My objective is to seamlessly integrate real-time data pushed from the server to my application. Should I persist with native JavaScript, or would transitioning to TypeScript be more conducive to attaining the level of smooth live tracking you've achieved? also how can i add label to the vehicle . ?

**Comment by belom88** [comment]
* Performance doesn't depend on language JS/TS. TypeScript is translated to JavaScript to be able to run it.
* You can use TextLayer of deck.gl to add labels.
